### ISSUE TITLE
Computation of real normal modes from complex eigenvectors

### ISSUE THREAD

**Issue by nilswagner** [ladisk/pyEMA#7]
Details are given in the papers by

S. R. Ibrahim
Computation of Normal Modes from Identified Complex Modes
AIAA JOURNAL, VOL. 21, NO. 3 (1983)

and

Ulrich Fuellekrug
Computation of real normal modes from complex eigenvectors
Mechanical Systems and Signal Processing 22 (2008) 57–65

**Comment by klemengit** [comment]
A function `complex_to_normal_mode` was added in the `tools.py` module (commit 0689cdddf8b126e31204a2bdc4b302609a4f6ba3).

According to [1], the normal mode shape is the real part of the complex mode shape, when it is rotated so that the norm of its real part is maximized.

[1] Gladwell, H. Ahmadian GML, and F. Ismail. "Extracting Real Modes from Complex Measured Modes."

**Comment by jankoslavic** [comment]
Great @klemengit In the last commit #87f1643 I added it also as a method!
